# Generated by Django 2.1.3 on 2018-12-05 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv_oprtns', '0002_auto_20181128_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesave',
            name='file',
            field=models.FileField(max_length=200, upload_to=''),
        ),
    ]
