MEDICAL_PLAN = "medical_plan"
MEDICAL_DOCTORS = "medical_doctors"
MEMBER_NAME = "member_name"
DOCTOR_NAMES = "doctor_names"
MEMBER_DETAILS = "member_details"
PLAN_FIRST_CHOICE = "plan_first_choice"
PLAN_SECOND_CHOICE = "plan_second_choice"