STAR_STENR = "STAR_STENR"
STAR_STENRTP = "STAR_STENRTP"
STAR_PLUS_SPENRD = "STAR_PLUS_SPENRD"
STAR_PLUS_SPENRM = "STAR_PLUS_SPENRM"
STAR_KIDS = "STAR_KIDS"

DENTAL_DEENR = "DENTAL_DEENR"
DENTAL_DTF = "DENTAL_DTF"

MEDICAL_ETF = "MEDICAL_ETF"
MEDICAL_MMP4 = "MEDICAL_MMP4"
